In [1]:
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("gold_standard.csv", header = None, usecols = [0,1,2,3,4,5,6,7,8,9,10,11,12,17])

In [3]:
# holdout method
msk = np.random.rand(len(df)) < 0.8
train = df[msk]
test = df[~msk]

train_target = train.iloc[:,-1]
train_data = train.iloc[:, :-1]

test_target = test.iloc[:,-1]
test_data = test.iloc[:, :-1]

In [4]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(train_data)

In [5]:
kmeans.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int32)

In [6]:
train_labels = kmeans.predict(train_data)

In [7]:
cluster_0 = list()
cluster_1 = list()

tt = train_target.as_matrix()

for i,v in enumerate(train_labels):
    if v:
        cluster_1.append(tt[i])
    else:
        cluster_0.append(tt[i])

print("Cluster 0:",cluster_0,"\n\n Cluster 1:", cluster_1)

Cluster 0: [-1, -1, -1, -1, 1, -1, -1, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] 

 Cluster 1: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [8]:
test_labels = kmeans.predict(test_data)

In [9]:
cluster_0 = list()
cluster_1 = list()

tt = test_target.as_matrix()

for i,v in enumerate(test_labels):
    if v:
        cluster_1.append(tt[i])
    else:
        cluster_0.append(tt[i])

print("Cluster 0:",cluster_0,"\n\n Cluster 1:", cluster_1)



Cluster 0: [-1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] 

 Cluster 1: [-1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [10]:
from sklearn import svm
clf = svm.SVC()

clf.fit(train_data, train_target)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [11]:
clf.predict(test_data)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.array(test_target) == clf.predict(test_data)

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)